spring.application.name=gamma

spring.jpa.hibernate.ddl-auto=update

aruba.api.base-url=http://localhost:8089

#Diciamo a kafka di usare il json Serializer per chi invia i messaggi
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

#Diciamo a kafka di usare il json Deserializer per chi riceve i messaggi
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer

#Diciamo al consumer di fidarsi e deserilaizzare i dati provenienti dal nostro progetto
spring.kafka.consumer.properties.spring.json.trusted.packages=*

