spring.application.name=gamma

spring.jpa.hibernate.ddl-auto=update

spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8081/realms/gamma

aruba.api.base-url=http://localhost:8089
aruba.api.sign-path=${aruba.api.base-url}/api/aruba/sign
aruba.api.conserve-path=${aruba.api.base-url}/api/aruba/conserve

kafka.topic.attachment-to-sign=attachment-to-sign-topic
kafka.topic.document-signed=document-signed-topic

#Diciamo a kafka di usare il json Serializer per chi invia i messaggi
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

#Diciamo a kafka di usare il json Deserializer per chi riceve i messaggi
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer

#Diciamo al consumer di fidarsi e deserilaizzare i dati provenienti dal nostro progetto
spring.kafka.consumer.properties.spring.json.trusted.packages=*

resilience4j.circuitbreaker.instances.aruba-sign-circuit-breaker.sliding-window-size=1
resilience4j.circuitbreaker.instances.aruba-sign-circuit-breaker.minimum-number-of-calls=1
resilience4j.circuitbreaker.instances.aruba-sign-circuit-breaker.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.aruba-sign-circuit-breaker.wait-duration-in-open-state=5s
resilience4j.circuitbreaker.instances.aruba-sign-circuit-breaker.permitted-number-of-calls-in-half-open-state=3

resilience4j.circuitbreaker.instances.aruba-conservation-circuit-breaker.sliding-window-size=1
resilience4j.circuitbreaker.instances.aruba-conservation-circuit-breaker.minimum-number-of-calls=1
resilience4j.circuitbreaker.instances.aruba-conservation-circuit-breaker.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.aruba-conservation-circuit-breaker.wait-duration-in-open-state=5s
resilience4j.circuitbreaker.instances.aruba-conservation-circuit-breaker.permitted-number-of-calls-in-half-open-state=3


# OAuth2 Config
spring.security.oauth2.client.registration.aruba.client-id=gamma-client
spring.security.oauth2.client.registration.aruba.client-secret=client-secret
spring.security.oauth2.client.registration.aruba.authorization-grant-type=client_credentials
spring.security.oauth2.client.provider.aruba.token-uri=http://localhost:8081/realms/gamma/protocol/openid-connect/token
