spring.datasource.url=jdbc:postgresql://postgres:5432/gamma_db
spring.kafka.bootstrap-servers=kafka:9092
aruba.api.base-url=http://wiremock:8080
spring.security.oauth2.client.provider.aruba.token-uri=http://keycloak:8080/realms/gamma/protocol/openid-connect/token
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8081/realms/gamma
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://keycloak:8080/realms/gamma/protocol/openid-connect/certs